Send logging to stderr - stop interfering with wrapped output

diff --git a/bin/vault_exec b/bin/vault_exec
--- a/bin/vault_exec
+++ b/bin/vault_exec
@@ -6,18 +6,22 @@ VAULT_CREDENTIALS_PATH_DEFAULT=aws/creds/developer
 # this is also the default if not specified at all
 VAULT_CREDENTIALS_DURATION_DEFAULT=1h
 
+log_message() {
+  (>&2 echo $@)
+}
+
 if [ "" == "$VAULT_CREDENTIALS_PATH" ]; then
-  echo "You did not specify a VAULT_CREDENTIALS_PATH, using the default $VAULT_CREDENTIALS_PATH_DEFAULT"
+  log_message "You did not specify a VAULT_CREDENTIALS_PATH, using the default $VAULT_CREDENTIALS_PATH_DEFAULT"
   VAULT_CREDENTIALS_PATH=$VAULT_CREDENTIALS_PATH_DEFAULT
 fi
 
 if [ "" == "$VAULT_CREDENTIALS_DURATION" ]; then
-  echo "You did not specify a VAULT_CREDENTIALS_DURATION, using the default $VAULT_CREDENTIALS_DURATION_DEFAULT"
+  log_message "You did not specify a VAULT_CREDENTIALS_DURATION, using the default $VAULT_CREDENTIALS_DURATION_DEFAULT"
   VAULT_CREDENTIALS_DURATION=$VAULT_CREDENTIALS_DURATION_DEFAULT
 fi
 
 if [ "$DEBUG_VAULT_EXEC" = "true" ]; then
-  echo "VAULT_CREDENTIALS_PATH=$VAULT_CREDENTIALS_PATH"
+  log_message "VAULT_CREDENTIALS_PATH=$VAULT_CREDENTIALS_PATH"
 fi
 
 readField() {
@@ -28,7 +32,7 @@ readField() {
 resetCredentials() {
     vault write -format=json $VAULT_CREDENTIALS_PATH ttl=$VAULT_CREDENTIALS_DURATION > $CREDENTIALS_FILE
     if [ "0" -ne "$?" ]; then
-        echo "Failed to get new credentials from vault!  Quitting."
+        log_message "Failed to get new credentials from vault!  Quitting."
         rm $CREDENTIALS_FILE
         exit 1
     fi
@@ -51,21 +55,21 @@ calculateTimeLeft() {
 }
 
 if [ ! -f $CREDENTIALS_FILE ]; then
-    echo "Vault credentials file not found ($CREDENTIALS_FILE) - creating new credentials."
+    log_message "Vault credentials file not found ($CREDENTIALS_FILE) - creating new credentials."
     resetCredentials
 fi
 
 if [ ! -f $EXPIRATION_FILE ]; then
-    echo "Vault credentials expiration file not found ($EXPIRATION_FILE) - creating new credentials."
+    log_message "Vault credentials expiration file not found ($EXPIRATION_FILE) - creating new credentials."
     resetCredentials
 fi
 
 timeLeft=$(calculateTimeLeft)
 if [ "0" -gt "$timeLeft" ]; then
-    echo "Vault credentials have expired or are not valid - creating new credentials."
+    log_message "Vault credentials have expired or are not valid - creating new credentials."
     resetCredentials
 else
-    echo "Vault credentials will remain valid for: $timeLeft seconds"
+    log_message "Vault credentials will remain valid for: $timeLeft seconds"
 fi
 
 export AWS_ACCESS_KEY_ID=$(readField 'access_key')
@@ -74,10 +78,10 @@ export AWS_SESSION_TOKEN=$(readField 'security_token')
 
 if [ "$DEBUG_VAULT_EXEC" = "true" ]
 then
-    echo vault_exec version $VAULT_EXEC_VERSION
-    echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
-    echo AWS_SECRET_ACCES_KEY=$AWS_SECRET_ACCESS_KEY
-    echo AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
+    log_message vault_exec version $VAULT_EXEC_VERSION
+    log_message AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
+    log_message AWS_SECRET_ACCES_KEY=$AWS_SECRET_ACCESS_KEY
+    log_message AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
 fi
 
 eval $@
